package com.zanh.route_sharing.domain.enums;

public enum LoaiThongBao {
    EMAIL_VERIFICATION,
    MEMBER_REVIEW_RESULT,
    DRIVER_REVIEW_RESULT,
    VEHICLE_REVIEW_RESULT,
    BOOKING_REQUEST,
    BOOKING_ACCEPTED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED_BY_PASSENGER,
    BOOKING_CANCELLED_BY_DRIVER,
    ROUTE_CANCELLED_BY_DRIVER,
    ROUTE_LOCKED,
    TRIP_STARTED,
    TRIP_CANCELLED_BEFORE_START,
    DRIVER_ARRIVED_PICKUP,
    PASSENGER_BOARDED,
    PASSENGER_NO_SHOW,
    DRIVER_APPROACHING,
    PICKUP_CONFIRMATION_REQUEST,
    SIGNAL_LOST,
    SOS_ALERT,
    COMPLAINT_UPDATE,
    ACCOUNT_SUSPENDED,
    SYSTEM
}
